# Generated by Django 4.0.2 on 2022-04-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom_t',
            fields=[
                ('room_id', models.CharField(db_column='room_id', max_length=10, primary_key=True, serialize=False)),
                ('room_c', models.IntegerField(blank=True, db_column='room_capacity', null=True)),
            ],
            options={
                'db_table': 'classroom_t',
            },
        ),
        migrations.CreateModel(
            name='course_t',
            fields=[
                ('course_ID', models.CharField(db_column='course_id', max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, db_column='course_name', max_length=50, null=True)),
                ('credit_hours', models.IntegerField(blank=True, db_column='credit_hours', null=True)),
            ],
            options={
                'db_table': 'course_t',
            },
        ),
        migrations.CreateModel(
            name='faculty_t',
            fields=[
                ('faculty_id', models.CharField(db_column='faculty_id', max_length=4, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(blank=True, db_column='faculty_name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'faculty_t',
            },
        ),
        migrations.CreateModel(
            name='resources_t',
            fields=[
                ('room_capacity', models.IntegerField(db_column='room_capacity', primary_key=True, serialize=False)),
                ('room_count', models.IntegerField(db_column='room_count')),
            ],
            options={
                'db_table': 'resources_t',
            },
        ),
        migrations.CreateModel(
            name='school_t',
            fields=[
                ('school_title', models.CharField(db_column='school_title', max_length=5, primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, db_column='school_name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'school_t',
            },
        ),
        migrations.CreateModel(
            name='department_t',
            fields=[
                ('dept_id', models.CharField(db_column='dept_id', max_length=5, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, db_column='dept_name', max_length=50, null=True)),
                ('school_title', models.ForeignKey(blank=True, db_column='school_title', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='databaseapp.school_t')),
            ],
            options={
                'db_table': 'department_t',
            },
        ),
        migrations.CreateModel(
            name='coofferedwith_t',
            fields=[
                ('cooffered_c', models.CharField(db_column='cooffered_c', max_length=10, primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='databaseapp.course_t')),
            ],
            options={
                'db_table': 'coofferedwith_t',
            },
        ),
        migrations.CreateModel(
            name='section_t',
            fields=[
                ('section_number', models.IntegerField(blank=True, db_column='section_number', null=True)),
                ('section_no', models.IntegerField(db_column='section_no', primary_key=True, serialize=False)),
                ('session_name', models.CharField(db_column='session_name', max_length=10)),
                ('days', models.CharField(db_column='days', max_length=2)),
                ('syear', models.CharField(db_column='syear', max_length=4)),
                ('capacity', models.IntegerField(blank=True, db_column='capacity', null=True)),
                ('enroll_capacity', models.IntegerField(blank=True, db_column='enroll_capacity', null=True)),
                ('block_status', models.IntegerField(blank=True, db_column='block_status', null=True)),
                ('start_time', models.CharField(blank=True, db_column='start_time', max_length=4, null=True)),
                ('end_time', models.CharField(blank=True, db_column='end_time', max_length=4, null=True)),
                ('course_id', models.ForeignKey(blank=True, db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='databaseapp.course_t')),
                ('dept_id', models.ForeignKey(blank=True, db_column='dept_id', on_delete=django.db.models.deletion.DO_NOTHING, to='databaseapp.department_t')),
                ('faculty_id', models.ForeignKey(blank=True, db_column='faculty_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='databaseapp.faculty_t')),
                ('room_id', models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='databaseapp.classroom_t')),
            ],
            options={
                'db_table': 'section_t',
                'unique_together': {('course_id', 'dept_id', 'session_name', 'syear', 'section_no')},
            },
        ),
    ]
